Add the issue checker to enterprise scripts folder
goalgorilla/open_social_scripts pull request #10
Opened 2017-08-09 14:11 UTC by Kingdutch

This script looks at the extra.patches entry in a composer.json file and parses patches in the form of "issuenr - human readable description" to retrieve the issue status and display it in a pretty table.

![screen shot 2017-08-09 at 15 53 10](https://user-images.githubusercontent.com/327697/29125909-431635de-7d1d-11e7-9ca1-c01d3e4b3144.png)

2017-08-21 12:27 UTC, Kingdutch commented
![screen shot 2017-08-21 at 14 27 22](https://user-images.githubusercontent.com/327697/29519240-e44041a8-867c-11e7-9258-f5f8278b1b13.png)

The improved version adds support for GitHub PRs

2017-08-22 05:31 UTC, bramtenhove requested changes
The index.js file has some indentation issues (around line 10) and extra blank lines around line 23.

2017-08-22 08:37 UTC, Kingdutch commented
I've fixed the whitespace issues, improved the usage help text and made the `composer.json` argument optional in the process.

2017-08-23 11:51 UTC, bramtenhove commented on issue_checker/readme.md
> +/path/to/issue_checker/index.js /path/to/composer.json
@Kingdutch the composer.json was not needed right? Can you update it in the readme?

2017-08-23 11:56 UTC, Kingdutch commented on issue_checker/readme.md
> +/path/to/issue_checker/index.js /path/to/composer.json
You're right, I've fixed it

2017-08-23 12:15 UTC, bramtenhove approved these changes

2017-08-23 13:48 UTC, merged